### ISSUE TITLE
index.html?

### ISSUE THREAD

**Issue by TotallyInformation** [mattdesl/prot#2]
Hi, really liking PROT which is much easier to use than raw Budo.

However, there doesn't seem to be a way to pass in an existing index.html? I don't necessarily want to have to build the whole html using REACT and Budo does pick up existing index.html files.

**Comment by mattdesl** [comment]
Yes, ideally the tool would handle `index.html` properly. It is easy to fix this by removing `forceDefaultIndex` from the dev script. However, it would require a bit more attention in the docs so that user's aren't surprised when `prot -b index.html` starts messing up their workflow.

Since this is just a proof-of-concept, and not something I plan to maintain, I probably won't do anything to change this. :smile: Cheers!

**Comment by TotallyInformation** [comment]
Thanks Matt, if you aren't doing anything more on this I might look elsewhere - shame though as this is much better to use overall.

**Comment by mattdesl** [comment]
You can take over the repo/module if you'd like to maintain it going forward. :smile: I just don't want the burden right now since I have a lot of other stuff on my place.

Also check out these related tools:
- https://github.com/remixz/run-js
- https://github.com/satya164/quik

**Comment by TotallyInformation** [comment]
Hi Matt, sorry about the delayed response.

I'd have to have a look at the code to see how much it is beyond my capability ;)
I'm also stretched for time so I wouldn't want to take it on if I couldn't keep it going.

I'll also take a look at those other tools, thanks for the steer. There are so many tools to choose from, it is all too easy to spend your life trying to track down the right toolset. :(
